name: CustomBlastFurnace
version: 1.0.1
main: io.github.sonic3modder.customblastfurnace.CustomBlastFurnace
description: Customize blast furnace recipes - Java 17+ (MC 1.18+)
author: Sonic3Modder
website: https://github.com/Sonic3Modder
api-version: 1.18
folia-supported: true

dependencies:
  server: []
  bootstrap: []