name: CustomBlastFurnace
version: 1.0.1
main: io.github.sonic3modder.customblastfurnace.CustomBlastFurnace
api-version: 1.18
author: Sonic3Modder
description: Customize blast furnace recipes - Java 17+ (MC 1.18+)
folia-supported: true

commands:
  customblastfurnace:
    description: Reload the plugin configuration
    usage: /customblastfurnace reload
    aliases: [cbf, blastfurnace]
    permission: customblastfurnace.reload

permissions:
  customblastfurnace.reload:
    description: Allows reloading the plugin configuration
    default: op